### ISSUE TITLE
部分功能不可用

### ISSUE THREAD

**Issue by loliskye** [Hsury/Bilibili-Toolkit#8]
疑似 B 站接口调整，启动运行后异常信息：

``` python
Task exception was never retrieved
future: <Task finished coro=<Notifier.__exec_one_step() done, defined at notifier.py:42> exception=TypeError("unsupported operand type(s) for +=: 'NoneType' and 'NoneType'")>
Traceback (most recent call last):
  File "notifier.py", line 46, in __exec_one_step
  File "notifier.py", line 20, in notify
  File "user.py", line 113, in accept
  File "tasks\live_daily_job.py", line 280, in send_gift
  File "tasks\live_daily_job.py", line 239, in send_medal_gift
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'NoneType'
```

不可用功能：
- 网页端观看任务未完成（概率出现）
- 3查看持有勋章状态.不可用

:)

**Comment by Hsury** [comment]
1. B站对每日观看任务的统计存在延时，建议对该现象进行进一步的确认
2. 如遇直播助手组件运行异常，请前往[yjqiang/bili2.0](https://github.com/yjqiang/bili2.0)获取技术支持

**Comment by loliskye** [comment]
目前突然恢复正常，已无任何异常.....

迷~
thx

**Comment by loliskye** [comment]
现在又出现了上面的问题，试了下单独运行最新的 bili2.0 是没问题的；

然后想要打包最新的 bili2.0 替换 `bilibili-live-tool-windows` 下的 `live.exe`

但是使用 Pyinstaller 打包成功后执行时报错....  未解决 o(￣▽￣*)ゞ))￣▽￣*)o

求大佬抽空更新下 bili2.0 模块~
